name: Export my notion workspace

on:
  schedule:
    - cron: "0 */24 * * *"  # Call the export every 6 hours
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: igor-kupczynski/notion-exporter@v1.0.2
        with:
          pages: "81a0062aac6c44308da00f80af7395e3"  # Pages IDs identified in (step 2)  
          output-dir: writeups
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
